# Generated by Django 6.0.2 on 2026-02-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0002_matricula'),
    ]

    operations = [
        migrations.RenameField(
            model_name='matricula',
            old_name='data_matricula',
            new_name='periodo',
        ),
    ]
